### ISSUE TITLE
MVP List

### ISSUE THREAD

**Issue by TahjDev** [linb1/Datcord#1]
- Your MVP's are a bit out of order. 
- Servers should be before direct messaging just because servers are more essential to discord. 
- Servers should also be before live chat, just because you need the servers to build the live chat on. 
- Inside of user auth, it says users will error out. Will users be shown errors?

**Comment by linb1** [comment]
Fixed the order of the MVPs, added that users will be shown error with red text when they input invalid information

**Comment by linb1** [comment]
Closed by accident
